CRYPTO_LIST = [
    'BTC/USDT', 'ETH/USDT', 'BNB/USDT', 'XRP/USDT', 'ADA/USDT',
    'DOGE/USDT', 'MATIC/USDT', 'SOL/USDT', 'DOT/USDT', 'LTC/USDT',
    'LINK/USDT', 'AVAX/USDT'
]

TIMEFRAME_OPTIONS = ['1h', '1d', '1w']